### ISSUE TITLE
Onedrive Business Account 

### ISSUE THREAD

**Issue by hirockstar** [morganshaner/onedrive-fetch#1]
It's not working with onedrive business account Folder Share URL.

**Comment by morganshaner** [comment]
Thanks for your info. Can you check the console for an error message when you try to use it? This package should log an error if there is a problem with it or with the arguments. If there is no error message, it may be another issue with your code. Note the fetch process is asynchronous.

Also try using this more simplified example:
```
const odfetch = require("onedrive-fetch");

odfetch("put_share_URL_here")
  .then(
    function (result) {
        //Your code here, for example:
        result.forEach((item) => {
          console.log({ name: item.name, url: item.webUrl });
        });
      });
```

**Comment by hirockstar** [comment]
here is test [url ](https://rdrive-my.sharepoint.com/:f:/g/personal/ftp_rdrive_org/EnRlTLlTeA1EmkSrXT_p6vIBegvDJa04cYnIX_E6K68Xbw?e=MYeBWk)check on your side

**Comment by morganshaner** [comment]
Hello. I see. Sorry to say, my package will not work with OneDrive for Business.

You'll need to use instead either:
1. This package: https://www.npmjs.com/package/onedrive-api
2. Microsoft Graph: https://learn.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/?view=odsp-graph-online

**Comment by hirockstar** [comment]
Oh thanks man
